### ISSUE TITLE
How to turn cloud_cluster from segment_submap.cpp into standard PointNetVLAD input vector (4096-d)?

### ISSUE THREAD

**Issue by ResearcherYan** [kxhit/pointnetvlad#1]
Thanks for your sharing of KITTI preprocessing code of PointNetVLAD. In the [source issues of PointNetVLAD](https://github.com/mikacuy/pointnetvlad/issues/3#issuecomment-540594230), you give some P-R Curves on KITTI. Could you talk about the method of transforming the data structure pcl::PointXYZL (specifically variable "cloud_cluster" in `segment_submap.cpp`) into standard PointNetVLAD input vector (4096-d)?

**Comment by kxhit** [comment]
Hi, 
If I remember if correctly, PointNetVLAD will firstly create submap by registering pointclouds into a local map, and then remove the groud, and finally randomly sample 4096 points from it to be the input vector. I believe this part [code](https://github.com/kxhit/pointnetvlad/blob/f5bf973aa690d76b23f7b00c8a8d2fe373780d65/submap_generation/generate_submaps.m#L31) will help you. Cheers.

**Comment by ResearcherYan** [comment]
@kxhit Thanks a lot. I'll go ahead with the matlab code.
